import { Injectable, signal, inject } from "@angular/core";
import { Message } from "./message.model"
import { HttpClient } from "@angular/common/http"

@Injectable({
  providedIn: "root",
})
export class ChatService {
  httpClient     = inject(HttpClient);
  userWeChatWith = signal<string>(""); // The current user we chat with
  currentUser    = signal<string>(""); // The account connected on the app
  usersList      = signal<string[]>([
    "Augustin",
    "Clement",
    "Benedicte",
    "Philippe",
    "Manon",
    "Levan",
  ]);
  prevMessages   = signal<Message[]>([
    {id:0 , speaker:0, content: "Quel est on framework prefere ?"},
    {id:1 , speaker:1, content: "Angular, sans aucun doute."},
    {id:2 , speaker:0, content: "Ravi. \n \n \n"},
    {id:3 , speaker:1, content: "sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss \n sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"},
    {id:4 , speaker:0, content: "sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss \n sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"},
    {id:5 , speaker:1, content: ""},
    {id:6 , speaker:0, content: ""},
    {id:7 , speaker:1, content: "s"},
    {id:8 , speaker:0, content: "s"},
        {id:0 , speaker:0, content: "Quel est on framework prefere ?"},
    {id:1 , speaker:1, content: "Angular, sans aucun doute."},
    {id:2 , speaker:0, content: "Ravi. \n \n \n"},
    {id:3 , speaker:1, content: "sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss \n sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"},
    {id:4 , speaker:0, content: "sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss \n sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"},
    {id:5 , speaker:1, content: ""},
    {id:6 , speaker:0, content: ""},
    {id:7 , speaker:1, content: "s"},
    {id:8 , speaker:0, content: "s"},
        {id:0 , speaker:0, content: "Quel est on framework prefere ?"},
    {id:1 , speaker:1, content: "Angular, sans aucun doute."},
    {id:2 , speaker:0, content: "Ravi. \n \n \n"},
    {id:3 , speaker:1, content: "sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss \n sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"},
    {id:4 , speaker:0, content: "sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss \n sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"},
    {id:5 , speaker:1, content: ""},
    {id:6 , speaker:0, content: ""},
    {id:7 , speaker:1, content: "s"},
    {id:8 , speaker:0, content: "s"},
        {id:0 , speaker:0, content: "Quel est on framework prefere ?"},
    {id:1 , speaker:1, content: "Angular, sans aucun doute."},
    {id:2 , speaker:0, content: "Ravi. \n \n \n"},
    {id:3 , speaker:1, content: "sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss \n sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"},
    {id:4 , speaker:0, content: "sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss \n sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"},
    {id:5 , speaker:1, content: ""},
    {id:6 , speaker:0, content: ""},
    {id:7 , speaker:1, content: "s"},
    {id:8 , speaker:0, content: "s"},
        {id:0 , speaker:0, content: "Quel est on framework prefere ?"},
    {id:1 , speaker:1, content: "Angular, sans aucun doute."},
    {id:2 , speaker:0, content: "Ravi. \n \n \n"},
    {id:3 , speaker:1, content: "sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss \n sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"},
    {id:4 , speaker:0, content: "sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss \n sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"},
    {id:5 , speaker:1, content: ""},
    {id:6 , speaker:0, content: ""},
    {id:7 , speaker:1, content: "s"},
    {id:8 , speaker:0, content: "s"},
        {id:0 , speaker:0, content: "Quel est on framework prefere ?"},
    {id:1 , speaker:1, content: "Angular, sans aucun doute."},
    {id:2 , speaker:0, content: "Ravi. \n \n \n"},
    {id:3 , speaker:1, content: "sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss \n sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"},
    {id:4 , speaker:0, content: "sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss \n sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"},
    {id:5 , speaker:1, content: ""},
    {id:6 , speaker:0, content: ""},
    {id:7 , speaker:1, content: "s"},
    {id:8 , speaker:0, content: "s"},
        {id:0 , speaker:0, content: "Quel est on framework prefere ?"},
    {id:1 , speaker:1, content: "Angular, sans aucun doute."},
    {id:2 , speaker:0, content: "Ravi. \n \n \n"},
    {id:3 , speaker:1, content: "sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss \n sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"},
    {id:4 , speaker:0, content: "sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss \n sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"},
    {id:5 , speaker:1, content: ""},
    {id:6 , speaker:0, content: ""},
    {id:7 , speaker:1, content: "s"},
    {id:8 , speaker:0, content: "s"},
        {id:0 , speaker:0, content: "Quel est on framework prefere ?"},
    {id:1 , speaker:1, content: "Angular, sans aucun doute."},
    {id:2 , speaker:0, content: "Ravi. \n \n \n"},
    {id:3 , speaker:1, content: "sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss \n sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"},
    {id:4 , speaker:0, content: "sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss \n sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"},
    {id:5 , speaker:1, content: ""},
    {id:6 , speaker:0, content: ""},
    {id:7 , speaker:1, content: "s"},
    {id:8 , speaker:0, content: "s"},
        {id:0 , speaker:0, content: "Quel est on framework prefere ?"},
    {id:1 , speaker:1, content: "Angular, sans aucun doute."},
    {id:2 , speaker:0, content: "Ravi. \n \n \n"},
    {id:3 , speaker:1, content: "sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss \n sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"},
    {id:4 , speaker:0, content: " \n sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"},
    {id:5 , speaker:1, content: ""},
    {id:6 , speaker:0, content: ""},
    {id:7 , speaker:1, content: "s"},
    {id:8 , speaker:0, content: "s"},

  ])
}
